name: Notion to Static
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install deps
        run: npm ci || npm i
      - name: Build static site from Notion
        env:
          SITE_NAME: ${{ secrets.SITE_NAME }}
          SITE_URL: ${{ secrets.SITE_URL }}
          SKIMLINKS_PUB_ID: ${{ secrets.SKIMLINKS_PUB_ID }}
          GA4_MEASUREMENT_ID: ${{ secrets.GA4_MEASUREMENT_ID }}
          AMAZON_TRACKING_ID: ${{ secrets.AMAZON_TRACKING_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ARTICLES: ${{ secrets.NOTION_DB_ARTICLES }}
          NOTION_DB_PRODUCTS: ${{ secrets.NOTION_DB_PRODUCTS }}
          NOTION_DB_KEYWORDS: ${{ secrets.NOTION_DB_KEYWORDS }}
        run: npm run build
      - name: Commit generated files
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m 'chore: update static site from Notion'
            git push
          else
            echo 'No changes'
          fi
